import os

files_to_delete = [
    ".markdownlint.json",
    "afrog.json",
    "AlliN.json",
    "another-redis-desktop-manager.json",
    "antsword.json",
    "AsyncRAT.json",
    "av_evasion_tool.json",
    "baidudisk.json",
    "bantam.json",
    "behinder.json",
    "beroot.json",
    "BrowserGhost.json",
    "broxy.json",
    "burpsuite-np.json",
    "burpsuite.json",
    "C3.json",
    "caesium.json",
    "cmseek.json",
    "cobaltstrike.json",
    "commix.json",
    "confuserex-cli.json",
    "confuserex-gui.json",
    "Covenant.json",
    "cpuz-cn.json",
    "crawlergo.json",
    "ct.json",
    "cudatext-cn.json",
    "curl-impersonate.json",
    "dalfox.json",
    "ddns-go.json",
    "DeimosC2.json",
    "dev-sidecar.json",
    "dig.json",
    "dirbuster.json",
    "dirmap.json",
    "dirsearch.json",
    "dismap.json",
    "dnsx.json",
    "dotnet-runtime.json",
    "easy-context-menu.json",
    "edx.json",
    "ehole.json",
    "emeditor.json",
    "everything.json",
    "extensions.json",
    "extremedumper.json",
    "fab.json",
    "fastgithub.json",
    "ffuf.json",
    "filename.txt",
    "filezilla.json",
    "finalshell.json",
    "FlowUs.json",
    "FluentSearch.json",
    "fscan.json",
    "fuxploider.json",
    "gda.json",
    "getsploit.json",
    "girsh.json",
    "git-repo-clean.json",
    "gitGraber.json",
    "githacker.json",
    "gitminer.json",
    "gitrob.json",
    "goby.json",
    "goDoH.json",
    "godzilla.json",
    "goproxy.json",
    "govenom.json",
    "gowitness.json",
    "GTFOBLookup.json",
    "hackbrowserdata.json",
    "HashCalculator.json",
    "hetty.json",
    "houndsploit.json",
    "httpx.json",
    "hydra.json",
    "igdm.json",
    "interactsh.json",
    "jar-analyzer.json",
    "jndinjector.json",
    "john-the-ripper.json",
    "johnny.json",
    "katana.json",
    "kerbrute.json",
    "kscan.json",
    "ksubdomain.json",
    "LadonGo.json",
    "layerdomainfinder.json",
    "LaZagne.json",
    "LFISuite.json",
    "LiqunKit.json",
    "masscan.json",
    "mateuszex.json",
    "maye.json",
    "mdut.json",
    "merlin.json",
    "meterpeter.json",
    "mimikatz.json",
    "MonitorOff.json",
    "myexploit.json",
    "naabu.json",
    "natpass.json",
    "Neo-reGeorg.json",
    "netsparker.json",
    "netspy.json",
    "newfiletime.json",
    "nimscan.json",
    "NoSQLMap.json",
    "notepad--.json",
    "notify.json",
    "npcap.json",
    "nps.json",
    "nuclei.json",
    "observerward.json",
    "oneforall.json",
    "pagodo.json",
    "peass-ng.json",
    "phpenv.json",
    "platypus.json",
    "POC-T.json",
    "pocsuite3.json",
    "portforward.json",
    "postman-cn.json",
    "PowerRun.json",
    "Print-My-Shell.json",
    "PrintNotifyPotato.json",
    "proguard.json",
    "psudohash.json",
    "PwnXSS.json",
    "pyshell.json",
    "pyxis.json",
    "quake_rs.json",
    "quasar.json",
    "rad.json",
    "rakshasa.json",
    "RegConverter.json",
    "reGeorg.json",
    "reverse_ssh.json",
    "revshell.json",
    "rport.json",
    "rubick.json",
    "rustcat.json",
    "scan4all.json",
    "scaninfo.json",
    "screentogif.json",
    "searchdiggity.json",
    "ServerScan.json",
    "settings.json",
    "SharpStrike.json",
    "shellcodeloader.json",
    "shellfire.json",
    "SiteScan.json",
    "siyuan.json",
    "skyscorpion.json",
    "sliver.json",
    "socat.json",
    "sqlmap.json",
    "stowaway.json",
    "subfinder.json",
    "sublime-text.json",
    "suo5.json",
    "super-xray.json",
    "SuperSQLInjection.json",
    "svnExploit.json",
    "tasks.json",
    "Template.jsonc",
    "termite.json",
    "tidefinger.json",
    "transfer.json",
    "treesize.json",
    "txportmap.json",
    "uTools.json",
    "venom.json",
    "verycapture.json",
    "vscan.json",
    "w3cschool.json",
    "webpathbrute.json",
    "webshell_generate.json",
    "websocat.json",
    "weevely.json",
    "whois.json",
    "windterm.json",
    "windynamicdesktop.json",
    "wslpp.json",
    "wub.json",
    "xray.json",
    "xssor2.json",
    "XSStrike.json",
    "yakit.json",
    "ysomap.json",
    "yujianportscan.json"
]

# Specify the directory where the JSON files are located
directory_path = "C:\\Users\\ander\\Desktop\\DEV-tools\\bucket"  # Replace this with your actual directory path

def delete_json_files(directory_path, files_to_delete):
    if not os.path.exists(directory_path):
        print(f"Error: The specified directory '{directory_path}' does not exist.")
        return

    try:
        for root, dirs, files in os.walk(directory_path):
            for filename in files:
                if filename in files_to_delete and filename.endswith(".json"):
                    file_path = os.path.join(root, filename)
                    os.remove(file_path)
                    print(f"Deleted: {file_path}")
    except Exception as e:
        print(f"Error occurred: {e}")

if __name__ == "__main__":
    delete_json_files(directory_path, files_to_delete)
